Traceback (most recent call last):
  File "C:\Users\Mikel\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Mikel\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Mikel\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Mikel\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Mikel\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Mikel\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Mikel\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Mikel\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Exclude Spain and group by origin and group-type, summing pax numbers
abroad_groups = ignatian_19_20_21_22[ignatian_19_20_21_22["from"] != "Spain"]\
                .groupby(["from", "group"])["pax"].sum().to_frame()

# Unstack inner level of index, then sum column values to a new column "total"
abroad_groups_wide[("pax", "total")] = abroad_groups.unstack().sum(axis=1)

# Sort values by the "total" column
abroad_groups_wide_sorted = abroad_groups_wide.sort_values(("pax", "total"))
    
# Plot
fig, ax = plt.subplots(figsize=(11.5, 10))

abroad_groups_wide_sorted.drop(("pax", "total"), axis=1)\
        .plot(kind="barh", stacked=True, ax=ax, color=palette_ign)

ax.grid(axis="x")
ax.set_axisbelow(True)
ax.tick_params(axis='x', labelsize=14)
ax.tick_params(axis='y', labelsize=12)
ax.set_title("Ignatian Way from Loyola:\n2019+2020+2021+2022 (Spain not included)", size=15)
ax.set_xlabel("PAX", size=14)
ax.set_ylabel("", size=14)
ax.legend(["Solo", "Couples", "Small groups", "Large groups"], fontsize=14, loc='lower right')

sns.despine()
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [9][0m, in [0;36m<cell line: 6>[1;34m()[0m
[0;32m      2[0m abroad_groups [38;5;241m=[39m ignatian_19_20_21_22[ignatian_19_20_21_22[[38;5;124m"[39m[38;5;124mfrom[39m[38;5;124m"[39m] [38;5;241m!=[39m [38;5;124m"[39m[38;5;124mSpain[39m[38;5;124m"[39m]\
[0;32m      3[0m                 [38;5;241m.[39mgroupby([[38;5;124m"[39m[38;5;124mfrom[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mgroup[39m[38;5;124m"[39m])[[38;5;124m"[39m[38;5;124mpax[39m[38;5;124m"[39m][38;5;241m.[39msum()[38;5;241m.[39mto_frame()
[0;32m      5[0m [38;5;66;03m# Unstack inner level of index, then sum column values to a new column "total"[39;00m
[1;32m----> 6[0m [43mabroad_groups_wide[49m[([38;5;124m"[39m[38;5;124mpax[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mtotal[39m[38;5;124m"[39m)] [38;5;241m=[39m abroad_groups[38;5;241m.[39munstack()[38;5;241m.[39msum(axis[38;5;241m=[39m[38;5;241m1[39m)
[0;32m      8[0m [38;5;66;03m# Sort values by the "total" column[39;00m
[0;32m      9[0m abroad_groups_wide_sorted [38;5;241m=[39m abroad_groups_wide[38;5;241m.[39msort_values(([38;5;124m"[39m[38;5;124mpax[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mtotal[39m[38;5;124m"[39m))

[1;31mNameError[0m: name 'abroad_groups_wide' is not defined
NameError: name 'abroad_groups_wide' is not defined

